### ISSUE TITLE
[Failure]Manhour Controller failure: no superior error

### ISSUE THREAD

**Issue by ShuqingYe1997** [ceej7/ProjMGT#15]
Commit: xxx
Priority: high
Description: When I'm using this interface below to create a new manhour for a project member, it shows "no sup" error but I'm pretty sure this member DO have a superior in the current project.
`/manhour/{eid}/{pid}/{aid}/{fid}`

@ceej7  Plz fix this bug, thx

**Comment by ceej7** [comment]
fixed in 1274ee4ae67b74c8ce645e98c1f04953003baa7d
