### ISSUE TITLE
[Time]Something might be wrong in time parsing: this is NOT the time I chose!

### ISSUE THREAD

**Issue by ShuqingYe1997** [ceej7/ProjMGT#16]
Commit: xxx
Priority: medium
Description:  I didn't notice this bug until last night, and the situation was: I was creating a new property occupation for an employee, but the expire time either displayed on browser or stored in db is **8 hours behind** the selected time.

e.g. the time I chose was (console.log()): 

> expire_time:  Fri May 01 2020 00:00:00 GMT+0800 (中国标准时间)

But the time on browser was: 

> 2020-04-30 16:00:00

The time in db was: 

> 2020-04-30 16:00:00

I was using these two interfaces: `/property/occupy/{employee_id}/{project_id}/{property_id}` and `/property/occupy/{poid}` in **Property Controller**

P.S. The **same** bug can also be found in `/manhour/{eid}/{mid}` and `/manhour/{eid}/{pid}/{aid}/{fid}` in **Manhour Controller**

@ceej7

**Comment by ceej7** [comment]
timezone parsing error,
fixed in commit b46f694
